repos:
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 84080c769d17e250eb32ac0d10662c7bf03ad346  # frozen: 0.31.3
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
    hooks:
      - id: detect-private-key
      - id: trailing-whitespace
      - id: end-of-file-fixer
