name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-packages:
    name: test-formulae
    strategy:
      fail-fast: false
      matrix:
        package: [bats-support, bats-assert, bats-detik, bats-file]
        os: [macos-12, macos-13, macos-14, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      PACKAGE: ${{ matrix.package }}
      TERM: xterm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Brew version output
        run: brew --version
      - name: INSTALL bats-core
        run: |
          brew list bats && brew uninstall bats || echo "bats is not present"
          brew install bats-core
      - name: INSTALL bats-support
        if: ${{ env.PACKAGE == 'bats-assert' || env.PACKAGE == 'bats-file' }}
        run: brew install --build-from-source --verbose bats-support
      - name: INSTALL local formula
        run: brew install --build-from-source --verbose $PACKAGE
      - name: AUDIT
        run: brew audit --new $PACKAGE
      - name: INSTALL
        run: brew install --build-from-source --verbose $PACKAGE
      - name: TEST
        run: brew test Formula/$PACKAGE.rb
